version: "3.8"
services:
    postgres:
        image: postgres:15.2-alpine
        container_name: postgres_solvery
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pwd123
            - POSTGRES_DB=solvery
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
            - DB_SOURCE=postgresql://root:pwd123@postgres_solvery:5432/solvery?sslmode=disable
        depends_on:
            - postgres
#        entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
#        command: [ "/app/main" ]
