// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Entry struct {
	ID        int64     `json:"id"`
	UserEmail string    `json:"user_email"`
	Amount    int32     `json:"amount"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Name      string    `json:"name"`
	Class     string    `json:"class"`
	Email     string    `json:"email"`
	Credit    int32     `json:"credit"`
	CreatedAt time.Time `json:"created_at"`
}
